# application.yml
aws:
  region: us-east-1
  userPoolId: 1cdbpsvt0r0g0kqftnf4mka6s8
  jwksUri: https://cognito-idp.us-east-1.amazonaws.com/1cdbpsvt0r0g0kqftnf4mka6s8/.well-known/jwks.json

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${aws.jwksUri}
